### ISSUE TITLE
Typo in READ.me

### ISSUE THREAD

**Issue by agmes4** [indoorequal/openlayers-indoorequal#23]
The READ.me has a Typo. The event which is triggered when changing the level is called in the [READ.me](https://github.com/indoorequal/openlayers-indoorequal/blob/main/README.md) levelchange
 but actually it is change:level. The same doku is also available at indoorequal.org which should be changed two.

**Comment by agmes4** [comment]
but the project is very cool thanks for your work :)

**Comment by francois2metz** [comment]
Thanks for spotting the issue. I fixed it.
