### ISSUE TITLE
 indoor maps are not displayed

### ISSUE THREAD

**Issue by alenigrelli** [indoorequal/openlayers-indoorequal#3]
Hello good afternoon, I am using the library to show indoor maps and when it loads it shows me as follows. Any recommendation to use the library or any help to solve the error?
![image](https://user-images.githubusercontent.com/15861031/134732082-a61fe822-2e59-4733-b21b-0d10684a42c3.png)
![image](https://user-images.githubusercontent.com/15861031/134732128-ac004a46-07d8-4b10-8e50-65e95b887fef.png)
Recognizes map levels but cannot be displayed. I am implementing it in angular using osm as map

**Comment by francois2metz** [comment]
Hi there,
The library doesn't provide any default style right now.
You need to write your own style for now.

**Comment by alenigrelli** [comment]
What style does Indoorequal use?

**Comment by alenigrelli** [comment]
![image](https://user-images.githubusercontent.com/15861031/134743522-f7051e88-4688-42d1-b0f7-7c0ccdb9de83.png)
This is how it looks by adding the following.
`indoorEqual.setStyle((feature, resolution) => {
      return new Style({
        fill: new Fill({ color: 'white' })
        
      });
    });`

![image](https://user-images.githubusercontent.com/15861031/134743712-91a27ce8-8fc9-4187-9890-fc7a88af0f07.png)
What style should I add to make it look like this?

**Comment by francois2metz** [comment]
The API to create your style is documented here https://openlayers.org/en/latest/apidoc/module-ol_style_Style-Style.html

**Comment by alenigrelli** [comment]
Thank you @francois2metz !
I have one last question, I want to use the texts that indoorequal uses, how can I recover those texts?
![image](https://user-images.githubusercontent.com/15861031/134783545-8a02d47c-8062-4511-9d32-42961fb08a2a.png)
![image](https://user-images.githubusercontent.com/15861031/134783555-ca0af83b-9807-4b31-aedd-11b5c1cee002.png)
![image](https://user-images.githubusercontent.com/15861031/134783568-b01e352e-5979-4b5a-9d6b-30ef7e56a703.png)

**Comment by francois2metz** [comment]
All the text come from the vector layer. You have to request the properties of the feature and get the `name` property.

The vector layers are documented there: https://indoorequal.com/doc/schema

If you manage to finish the style that match the one from the `mapbox-gl-indoorequal`, I hope you'll open a pull request to improve this plugin!

**Comment by francois2metz** [comment]
Hi, I added a default style in the new version 0.0.2. It does not include images yet, but it's a good starting point.

**Comment by alenigrelli** [comment]
Thank you!! Thanks for the changes!
