### ISSUE TITLE
modify style indoorequal

### ISSUE THREAD

**Issue by alenigrelli** [indoorequal/openlayers-indoorequal#5]
Hi!
I want modify indoorequal style. I want see the doors. where do I modify indoorequal style?
below an example of how it looks:
![image](https://user-images.githubusercontent.com/15861031/146801824-3d6bf67d-f87a-44d7-b06f-7cc8c8d4858b.png)
an example of how I want them to look:
![image](https://user-images.githubusercontent.com/15861031/146801965-5dc0af85-d904-4b7c-adcd-8a129edca6f3.png)
I want see the doors.
Thanks!

**Comment by francois2metz** [comment]
Hi @alenigrelli 

The doors should be correctly rendered. The difference is between the mapbox-gl plugin and the openlayers? Could you provide an access to the data?

**Comment by alenigrelli** [comment]
I am using openlayers library. I think the problem is there. what acces need you?

Here i am using openlayers library.
![146801824-3d6bf67d-f87a-44d7-b06f-7cc8c8d4858b](https://user-images.githubusercontent.com/15861031/146952403-50dcbb20-ce3c-49fb-afb2-b6a318860c22.png)

**Comment by francois2metz** [comment]
> I am using openlayers library. I think the problem is there. what acces need you?

I you check the demo: https://indoorequal.github.io/openlayers-indoorequal/ you should see some doors. If you don't see them it's maybe a problem with the data. That's why without access to the tiles, I cannot debug it.

**Comment by alenigrelli** [comment]
sorry! my mistake was that it did not load the sprites.

**Comment by alenigrelli** [comment]
Other question is : how do I add a new sprite?
this is my image with new sprite and add it to the json too.
![indoorequal](https://user-images.githubusercontent.com/15861031/146993874-5adc9cfa-3fb4-4c8e-9204-09a302be8ea7.png)

[indoorequal.txt](https://github.com/indoorequal/openlayers-indoorequal/files/7758060/indoorequal.txt) (this is the indoorequal.json)

What configuration am I missing?

**Comment by alenigrelli** [comment]
![image](https://user-images.githubusercontent.com/15861031/146996488-653d4c95-0b08-4510-8bc7-debc47758211.png)
I want see these sprites in the indoorequal.
what do I do to see them?

**Comment by francois2metz** [comment]
You can create your own sprite. The original images are on the mapbox-gl-indoorequal repository: https://github.com/indoorequal/mapbox-gl-indoorequal/tree/master/mapicons
And there is a command to generate the files: https://github.com/indoorequal/mapbox-gl-indoorequal#develop

**Comment by alenigrelli** [comment]
how do I do in openalyers-indoorqual? 
![image](https://user-images.githubusercontent.com/15861031/147002953-43cd0c45-2cc8-454c-ab6c-102350165800.png)
you can this image, I change the elevator for my new sprite. I want add my new sprite. How do I do the match sprite with icon?

**Comment by francois2metz** [comment]
Once you have generated the sprite via the mapbox-gl-indoorequal repository, you can copy the resulting files and load them with openlayers

**Comment by alenigrelli** [comment]
ok! thanks! Sorry the question!
Once you have the file generated by mapbox. How do I match the turnstile element with the sprite?

**Comment by francois2metz** [comment]
You probably have to replace the current icon with the new one, the matching is done via the filename, either via the `class` or the `subclass` of the POI (see https://github.com/indoorequal/indoorequal/blob/331af89b89ef9a1fe9ee6ec6437f908ecae1e253/layers/poi/class.sql#L30-L72).
 If it's not enough, you may have to create your own style using the `setStyle` function: https://github.com/indoorequal/openlayers-indoorequal#setstyle

**Comment by alenigrelli** [comment]
Thank you! I could do it!!
