### ISSUE TITLE
how change zindex sprites?

### ISSUE THREAD

**Issue by alenigrelli** [indoorequal/openlayers-indoorequal#9]
Hello! how are you?
how change the zindex of sprites ?
I want it is behind of my icons.
![image](https://user-images.githubusercontent.com/15861031/153596906-273bcabb-b909-4316-86e8-931674f3142a.png)
![image](https://user-images.githubusercontent.com/15861031/153596956-74048931-48e9-4986-aa6a-89ea13abecbc.png)

**Comment by francois2metz** [comment]
Hi @alenigrelli. Could you share some details about the code? Are you using the same layer?
